root/cms/urls.py
from django.urls import path,include
import cms.views.blog as blog
import cms.views.shorturl as sl
from cms.views.account import *
from cms.views.menu import *
from cms.views.ticket import *
app_name ="cms"
urlpatterns = [
    path("Home/", accounthome, name="accounthome"),
    path("Signin/", signin, name="login"),
    path("Signup/", signup, name="signup"),
    path("Logout/", signout, name="logout"),
    path("Profile/", profile, name="profile"),
    path("Rest-Password/", restpass, name="restpass"),
    path("Change-Password/", changepass, name="changepass"),
    path("Rest-Password/<uuid:uuid>/", subpass, name="subpass"),
    path("blog/",blog.blog_list_view,name="blog_list"),
    path('blog/<slug>/', blog.blog_detail_view,name="blog_detail"),
    path('blog/tag/<slug>', blog.blog_tag,name="blog_tag"),
    path('blog/cat/<slug>', blog.blog_category,name="blog_category"),
    path('blog/star/<slug>', blog.blog_star,name="blog_star"),
    ############comments
    path('blog/comment/<slug>', blog.blog_comment,name="blog_comment"),
    path('blog/comment/like/<id>', blog.blog_comment_like,name="blog_comment_like"),
    path('blog/comment/dislike/<id>', blog.blog_comment_dislike,name="blog_comment_dislike"),
    #MENU
    path("myticket/", myticket, name="myticket"),
    path("myticket/<uuid:token>/",myticketchanel, name="myticketchanel"),
    path("newticket/",newticket, name="newticket"),
    ##shorturl
    path('sl/make', sl.short_url_make,name="short_url_make"),
    path('sl/post', sl.short_url_post,name="short_url_post"),
    path('sl/show/<str:token>', sl.show, name="show"),
    ##search
    path('search', blog.blog_search,name="blog_search"),
    
]
# menu or raise 404
urlpatterns +=[
    path("<str:page>/", menus, name="menus"),
]

root/root/urls.py
from django.contrib import admin
from django.urls import path,include

####static debug mode###################################################
from django.conf import settings
from django.conf.urls.static import static

########################################################################

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('cms.urls')),
    path('ckeditor', include('ckeditor_uploader.urls'),name="ckeditor"),

    

    

]


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #add static template
    urlpatterns = urlpatterns + static(settings.TEMPLATE_URL, document_root=settings.TEMPLATE_ROOT)

root/cms/forms/messages.py
messages={
    'max_length' : 'تعداد کارکتر های وارد شده بیشتر از حد مجاز',
    'min_length' : 'کارکتر های وارد شده کمتر از حد مجاز',
    'required' : 'لطفا فیلد مورد نظر را پر کنید',
    'invalid' : 'مقدار درست وارد نشده لطفا تصحیح کنید',
    'invalid_image' : 'پسوند تصویر وارد شده قابل پشتیبانی نیست',
    'missing':'فایل مورد نظر یافت نشد'
}

root/cms/views/account.py
from django.shortcuts import render,redirect,Http404,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
#from django.contrib.auth.models import User
from django.contrib import messages
from cms.models import *
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from cms.utils import *
from cms.forms.account.forms import ChangeRestPasswordForm,FormProfile,UserLoginForm,UserRegistrationForm,RestPasswordForm,ChangePasswordForm
from django.contrib.auth import get_user_model
from cms.decorators import user_required
User = get_user_model()
#from django.views.decorators.http import require_http_methods
@login_required
def accounthome(request):
    return render(request, 'account/Home.html')

@user_required
def signin(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            f = form.cleaned_data
            user = authenticate(request, email=f['email'], password=f['password'])
            if user: 
                login(request, user)
                return redirect('cms:accounthome')
            else :
                messages.add_message(request, messages.ERROR, 'نام یا کلمه عبور درست وارد نشده','danger')
    else : 
        form = UserLoginForm()
    obj = {
        'form' : form
    }
    return render(request, 'account/Login.html',obj)

@user_required
def signup(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            f = form.cleaned_data
            if f['password'] == f['repassword']:
                user = User.objects.create_user(email=f['email'],password=f['password'])
                user.save()
                messages.add_message(request, messages.SUCCESS, 'اکانت شما ساخته شد','success')
                return redirect('cms:login')
            else :
                messages.add_message(request, messages.ERROR, 'پسورد های وارد شده با هم برابر نیستند','danger')
    else : 
        form = UserRegistrationForm()
    obj = {
        'form' : form
    }
    return render(request, 'account/Signup.html',obj)     

def signout(request):
    logout(request)
    return redirect('cms:login')

@user_required
def restpass(request):
    if request.method == "POST":
        form = RestPasswordForm(request.POST)
        if form.is_valid():
            domain = get_current_site(request)
            email = form.cleaned_data['email']
            if User.objects.filter(email=email):
                if pwsrest.objects.filter(email=email) : 
                    getpws=get_object_or_404(pwsrest,email=email)
                    datepws = getpws.date
                    timepws = getpws.time
                    datenow = timezone.now().date()
                    minpws = fixtimemin(timepws.minute)
                    refreshtime =  minpws - timezone.now().time().minute +1
                    if datenow > datepws:
                        delpws=pwsrest.objects.filter(email=email).delete()
                        if restpassemail(email=email,domain=domain):
                            messages.add_message(request, messages.SUCCESS, 'ایمیل به شما ارسال شد لطفا صندوق دریافت خود را چک کنید','success')
                            return redirect('cms:login')
                    elif timezone.now().time().hour < timepws.hour or timezone.now().time().hour > timepws.hour :
                        delpws=pwsrest.objects.filter(email=email).delete()
                        if restpassemail(email=email,domain=domain):
                            messages.add_message(request, messages.SUCCESS, 'ایمیل به شما ارسال شد لطفا صندوق دریافت خود را چک کنید','success')
                            return redirect('cms:login')
                    elif minpws < timezone.now().time().minute :
                        delpws=pwsrest.objects.filter(email=email).delete()
                        if restpassemail(email=email,domain=domain):
                            messages.add_message(request, messages.SUCCESS, 'ایمیل به شما ارسال شد لطفا صندوق دریافت خود را چک کنید','success')
                            return redirect('cms:login')
                    else :
                        messages.add_message(request, messages.WARNING, f' ایمیل بعدی {refreshtime} دقیقه دیگر ')
                else :
                    if restpassemail(email=email,domain=domain):
                        messages.add_message(request, messages.SUCCESS, 'ایمیل به شما ارسال شد لطفا صندوق دریافت خود را چک کنید','success')
                        return redirect('cms:login')
            else:
                messages.add_message(request, messages.ERROR, 'در وارد کردن ایمیل خود توجه کنید همچین ایمیلی موجود نیست','danger')
    else:
        form = RestPasswordForm()
    obj = {
        'form' : form
    }
    return render(request, 'account/Restpassword.html',obj)
    
@user_required
def subpass(request,uuid):
    getpws=get_object_or_404(pwsrest,uuid=uuid,status=False)
    if request.method == "POST":
        form = ChangeRestPasswordForm(request.POST)
        if form.is_valid():
            f=form.cleaned_data
            if f['password'] == f['repassword'] :
                setpws = get_object_or_404(User,email=getpws.email)
                setpws.set_password(f['password'])
                setpws.save()
                delpws=get_object_or_404(pwsrest,uuid=uuid).delete()
                messages.add_message(request, messages.SUCCESS, 'پسورد با موفقیت تغییر یافت','success')
                return redirect('cms:login')
            else : 
                messages.add_message(request, messages.ERROR, 'کلمه عبور با تکرار خود برابر نیست','danger')
    else :
        form = ChangeRestPasswordForm()
    obj = {
        'form' : form
    }     
    return render(request, 'account/Set_new_password.html',obj)
    
    
@login_required
def changepass(request):
    if request.method == "POST":
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            f = form.cleaned_data
            getuser = get_object_or_404(User,email=request.user.email)
            if getuser.check_password(f['oldpassword']) : 
                if f['password'] == f['repassword'] :
                    getuser.set_password(f['password'])
                    getuser.save()
                    messages.add_message(request, messages.INFO, 'پسورد شما تغییر کرد لطفا دوباره وارد شوید','info')
                    logout(request)
                    return redirect('cms:login') 
                else:
                    messages.add_message(request, messages.ERROR, 'تکرار پسورد با  پسورد جیدید برابر نیست','danger')
            else:
                messages.add_message(request, messages.ERROR, 'پسورد که وارد کرده اید اشتباه است','danger')
    else :
        form = ChangePasswordForm()
    obj = {
        'form' : form
    } 
    return render(request, 'account/Change_Password.html',obj)

@login_required
def profile(request):
    if request.method == "POST":
        form = FormProfile(request.POST,request.FILES,instance=request.user)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'پروفایل شما ابدیت شد','success')
            return redirect('cms:accounthome') 
    else : 
        form = FormProfile(instance=request.user)
    obj = {
        'form' : form
    } 
    return render(request,'account/profile.html',obj)

root/cms/views/blog.py
from django.shortcuts import render,redirect
from cms.models import *
from django.http import Http404,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.



def blog_list_view(request):

    query=Blog.objects.active_Blogs()

    menus=menu.objects.all()

    if query is None:
        print("not article")
        raise Http404("no post here")
    query=query.order_by("-publish_time")
    context={
        "blog":query,
        'menus':menus
    }

    return render(request,"blog/blog_list_view.html",context)


def blog_detail_view(request, slug):
    detail_query=Blog.objects.get_by_slug(slug=slug)



    
    if detail_query is None:
        raise Http404("there is no article here")
    qs_comment=Blog.objects.get(slug=slug)
    comments=qs_comment.comments.all().order_by("-posted_time")
    
    ######FOR TAGS
    my_blog = Blog.objects.filter(slug=slug)
    
    ####inja post ro gerfetam rikhtam to my blog
    index_my_blog = list(my_blog)[0]
    ####tamamtag haye poste ro gereftam
    tags_to_page = list(index_my_blog.my_tags.all())



    context={
        
        "blog":detail_query,
        "tags_to_page":tags_to_page,
        "comments":comments,
      
    }

    if detail_query is None:

        raise Http404()


    print(detail_query[0].seen) 
    qs_comment.seen += 1
    print(detail_query[0].seen )

    
    qs_comment.save() 
    


    return render(request,"blog/blog_detail_view.html",context)


###in func mibare besafhe ii ke blog haei k on tago drn neshoon mide
def blog_tag(request,slug):
    tag_get=Tag.objects.get_by_slug(slug=slug)
    if tag_get is None:
        return Http404("in tag vojood nadarad")

    qs = Blog.objects.filter(active=True, my_tags=tag_get).order_by("created_time")





    context={
        "blogs":qs
    }
    return render(request,"blog/blog_tags_veiw.html",context)



def blog_category(request,slug):
    cat_get=Category.objects.get(slug=slug)

    qs = Blog.objects.filter(active=True, category=cat_get).order_by("-time")





    context={
        "blogs":qs
    }
    return render(request,"blog/blog_tags_veiw.html",context)




@login_required(login_url="/Signin/")
def blog_star(request,slug):
    blog=Blog.objects.get(slug=slug)
    stared=False
    if blog.star.filter(id=request.user.id).exists():
        blog.star.remove(request.user)
        stared=False
    else:
        blog.star.add(request.user)
        stared=True

    
    return HttpResponseRedirect(reverse('cms:blog_detail',kwargs={'slug':blog.slug}))







@login_required(login_url="/Signin/")
def blog_comment(request,slug):
    blog=Blog.objects.get(slug=slug)
    user=request.user
    text=request.POST.get("comment_post")
    model_comment=CommentBlog.objects.create(blog=blog,text=text,sender=user)

    return HttpResponseRedirect(reverse('cms:blog_detail',kwargs={'slug':blog.slug}))











@login_required(login_url="/Signin/")
def blog_comment_like(request,id):
    comment=CommentBlog.objects.get(id=id)
    if comment.like.filter(id=request.user.id).exists():
        comment.like.remove(request.user)
        stared=False
    else:
        comment.like.add(request.user)
        stared=True
        if comment.dislike.filter(id=request.user.id).exists():
            comment.dislike.remove(request.user)
       


    
    return HttpResponseRedirect(reverse('cms:blog_detail',kwargs={'slug':comment.blog.slug}))
@login_required(login_url="/Signin/")
def blog_comment_dislike(request,id):
    comment=CommentBlog.objects.get(id=id)
    if comment.dislike.filter(id=request.user.id).exists():
        comment.dislike.remove(request.user)
        stared=False
    else:
        comment.dislike.add(request.user)
        stared=True
        if comment.like.filter(id=request.user.id).exists():
            comment.like.remove(request.user)

    
    return HttpResponseRedirect(reverse('cms:blog_detail',kwargs={'slug':comment.blog.slug}))



def blog_search(request):
    q=request.GET.get("q")
    if q is not None:

       blog=Blog.objects.search(q)
    else:
        blog=Blog.objects.active_Blogs()

    context={
        "blog":blog
    }

    return render(request,"blog/blog_list_view.html",context)

root/cms/views/menu.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from cms.models import *
import codecs
from django.template import loader
from django.conf import settings

def menus(request,page):
    menuadr = get_object_or_404(menu,name=page)
    menuf= menuadr.file.all().order_by("-date")[:1]
    #html = ''
    pk = None
    if menuf:
        for m in menuf:
            pk = m.pk
        gettemplate = templatedir.objects.get(pk=pk)
        #pagep = str(settings.BASE_DIR) +'\\template\\'+str(gettemplate.file)
        #file = codecs.open(str(pagep), "r","UTF-8")
        #html=file.readlines()
        address= 'page/'+str(gettemplate.file)
        template = loader.get_template(address)
    else : 
        return HttpResponseRedirect(menuadr.link) 
    return HttpResponse(template.render())
    

root/cms/views/shorturl.py
from django.shortcuts import render,redirect
from cms import models
from django.http import Http404,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from cms.utils import Shortner


def short_url_post(request):
    
    long=request.POST.get("long")
    print(long[0:4])

    
    if long[0:4] == ("http" or "HTTP")  :

        long=long
    else:

        print(long)
        long="http://"+long
    
        


        





    ismodel=models.ShortUrls.objects.filter(long=long).exists()
    if ismodel:
        
        short=models.ShortUrls.objects.get(long=long).short
        
    else:
        try:

            short=Shortner().issue_token()
            models.ShortUrls.objects.create(long=long,short=short)

        except:
            short=Shortner().issue_token()
            models.ShortUrls.objects.create(long=long,short=short)


    return render(request,"shorturl/shorturl.html",{"short":short})




def show(request,token):
    long=models.ShortUrls.objects.filter(short=token)[0]

    return redirect(long.long)








def short_url_make(request):





    return render(request,"shorturl/shorturl.html")

root/cms/templates/blog/blog_detail_view.html
{%for i in blog %}

<div>{{i.title}}</div>

<img src="{{i.image.url}}" alt="" style="width: 300px ; height: 300px;">

<div> {{i.body|safe}}</div>

<div> 
   <a href="{{ i.short_link_def }}">shot link:  </a>
</div>


{% if  tags_to_page %}
 <div>
    <p> برچسب ها</p>
    {% for tags in tags_to_page %}

       <a href="{% url 'cms:blog_tag' slug=tags.slug   %}">#{{ tags }}</a>

    {% endfor %}

    </div>
{% endif %}

<form action="{% url 'cms:blog_star' slug=i.slug %}" method="POST">
{% csrf_token %}
<button type="submit" name="post_slug" value="{{i.slug}}" > like  {{i.number_of_starts}} </button>






</form>
<div>stars number :{{i.number_of_starts}} </div>

comments
<br>
-------------------------------------------------------------

<br>
<form action="{% url 'cms:blog_comment' slug=i.slug %}" method="POST" > 
   {% csrf_token %}
   <p>matn : </p>  <input type="text"  name="comment_post">
   <button type="submit"> submit </button>
  
  
  
  
  
  
  
  </form>



-------------------------------------------------------------
<br>



{% for l in comments %}
<br>

<div id="{{l.id}}">


   {{l.text}}
   <br>
   {{l.sender}}
   <br>
   {{l.posted_time}}
   <br>
   <a href="{% url 'cms:blog_comment_like' id=l.id %}"> like {{l.number_of_likes}} </a>
   <a href="{% url 'cms:blog_comment_dislike' id=l.id %}"> dislike {{l.number_of_dislikes}} </a>

   
</div>
-------------------------------------------------------------


{%endfor%}
<br>
{%endfor%}

root/cms/templates/blog/blog_list_view.html
{% extends 'blog/base/base.html' %} {% block meta %}
<title>بلاگ</title>
{% endblock meta %} {% block body %}
<div class="top">
    <div class="bar card padding sand " id="myNavbar">
        <a href="javascript:void(0)" class="margin-left text-white bar-item button hover-white hover-text-black right hide-large hide-medium" onclick="qopen()">
            <i class="fa fa-bars "></i>
        </a>
        <a href="" class="bar-item large text-white right margin-left">Action</i></a>

        <form action="{% url 'cms:blog_search' %}" method="GET">

            <input type="text" class="bar-item input right right-align margin-right hide-small" style="width: 350px;" placeholder="جستوجو کنید" name="q" value="{{ request.GET.q }}">
            <button class="bar-item right button white hover-teal hover-text-white hide-small" type="submit"><i class="fa fa-search "></i></button>


        </form>


        <a href="{% url 'cms:signup' %}" class="bar-item white btn border border-sand" style="font-weight: bold;">ثبت نام</a>
        <a href="{% url 'cms:login' %}" class="bar-item white btn border border-sand" style="font-weight: bold;">ورود</a>
    </div>
</div>
<div class="sand border-top border-white hide-small center" style="margin-top: 59px;">
    <div class="bar">
        {% for menu in menus %}
        <a href="{% url 'cms:menus' page=menu.name %}" class="bar-item button hover-white hover-text-sand sand text-white" style="font-weight: bold;">{{menu.name}}</a> {% endfor %}
    </div>
</div>
<nav class="sidebar sand bar-block card animate-left hide-medium hide-large center" style="display:none" id="mySidebar">
    <a href="javascript:void(0)" onclick="qclose()" class="bar-item text-red button large padding-16 hover-red">بستن <i class="fa fa-close"></i></a> {% for menu in menus %}
    <a href="{% url 'cms:menus' page=menu.name %}" class="bar-item button hover-text-sand text-white hover-white" style="font-weight: bold;">{{menu.name}}</a> {% endfor %}
</nav>

<div class="container" style="margin-top: 59px;">
    <div class="row mobile">
        {% for i in blog %}
        <div class="col s2  mobile">
            <div class=" margin border border-sand center round">
                <img width="100%" class="round hide-large hide-medium" src="{{i.image.url}}" alt="{{i.image.path}}">
                <img width="100%" class="round hide-small" src="{{i.image.url}}" alt="{{i.image.path}}">
                <p>{{i.title}}</p>
                <b style="font-size: 10px;">نویسنده : <b>{{i.publisher}}</b></b>&nbsp;&nbsp;<b style="font-size: 10px;">بازدید : {{i.seen}} </b>
                <p style="font-size: 10px;">{{i.jcal_time}}</p>
                <a style="font-size: 13px;font-weight: bold;" class="text-sand" href="{% url 'cms:blog_detail' slug=i.slug %}">ادامه مطلب</a>
            </div>
        </div>
        {% endfor%}
    </div>
</div>
{% endblock body %} {% block script %}
<script>
    var mySidebar = document.getElementById("mySidebar");

    function qopen() {
        if (mySidebar.style.display === 'block') {
            mySidebar.style.display = 'none';
        } else {
            mySidebar.style.display = 'block';
        }
    }

    // Close the sidebar with the close button
    function qclose() {
        mySidebar.style.display = "none";
    }
</script>
{% endblock script %}

root/cms/templates/blog/blog_tags_veiw.html
{% for i in blogs %}
<div>
<h1>

{{i.title}}
<a href="{% url "cms:blog_detail" slug=i.slug %}"> see more</a>
<img src="{{i.image.url}}" alt="" style="width: 300px ; height: 300px;">
</h1>
</div>

{% endfor %}